### ISSUE TITLE
Error 500 after installing Xblock

### ISSUE THREAD

**Issue by wildboardm92** [edx/XBlock#325]
I installed xblock using this doc --> https://github.com/edx/edx-platform/wiki/Installing-a-new-XBlock 
But after I got a problem with LMS and CMS (Error 500).
Log file: 
```
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 419, in course_listing
    courses, in_process_course_actions = get_courses_accessible_to_user(request)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 577, in get_courses_accessible_to_user
    courses, in_process_course_actions = _accessible_courses_list(request)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 356, in _accessible_courses_list
    courses = filter(course_filter, modulestore().get_courses())
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 90, in inner
    retval = func(field_decorator=strip_key_collection, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 276, in get_courses
    for course in store.get_courses(**kwargs):
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split_draft.py", line 83, in get_courses
    return super(DraftVersioningModuleStore, self).get_courses(ModuleStoreEnum.BranchName.draft, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/src/mongodb-proxy/mongodb_proxy.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 932, in get_courses
    return self._get_structures_for_branch_and_locator(branch, self._create_course_locator, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 892, in _get_structures_for_branch_and_locator
    structures_list = self._load_items(envelope, [root], depth=0, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 763, in _load_items
    return [runtime.load_item(block_key, course_entry, **kwargs) for block_key in block_keys]
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py", line 130, in _load_item
    block = self.xblock_from_json(class_, course_key, block_key, block_data, course_entry_override, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py", line 241, in xblock_from_json
    error_msg=exc_info_to_str(sys.exc_info())
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/error_module.py", line 144, in from_json
    location=location
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/error_module.py", line 124, in _construct
    for_parent=for_parent,
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/runtime.py", line 635, in construct_xblock_from_class
    *args, **kwargs
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1001, in __init__
    super(XModuleDescriptor, self).__init__(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 299, in __init__
    super(XModuleMixin, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'for_parent'
```

**Comment by nedbat** [comment]
@wildboardm92 The edx-code mailing list will be a better place to get help with issues like these: https://groups.google.com/forum/#!forum/edx-code
